site_name: nn
theme : simplex
repo_url : https://github.com/torch/nn
use_directory_urls : false
markdown_extensions: [extra]
docs_dir : doc
pages:
- [index.md, Home]
- [module.md, Modules, Module Interface]
- [containers.md, Modules, Containers]
- [transfer.md, Modules, Transfer Functions]
- [simple.md, Modules, Simple Layers]
- [table.md, Modules, Table Layers]
- [convolution.md, Modules, Convolution Layers]
- [criterion.md, Criterion, Criterions]
- [overview.md, Additional Documentation, Overview]
- [training.md, Additional Documentation, Training]
- [testing.md, Additional Documentation, Testing]
